# Generated by Django 3.1.6 on 2021-02-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_img',
            field=models.ImageField(null=True, upload_to='yes'),
        ),
    ]
