# Generated by Django 3.1.6 on 2021-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skills_skill_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_pic', models.ImageField(upload_to='user/profile_pic')),
                ('user_name2', models.CharField(max_length=50)),
                ('user_profession', models.CharField(max_length=50)),
                ('about_me_bio', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_img',
            field=models.ImageField(null=True, upload_to='portfolio_images'),
        ),
    ]
