# Generated by Django 3.1.6 on 2021-02-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210213_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe2',
            new_name='AboutMe',
        ),
    ]
