# Generated by Django 3.1.6 on 2021-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210213_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_pic'),
        ),
    ]
