# Generated by Django 3.1.6 on 2021-02-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210213_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mywork',
            name='work_img',
            field=models.ImageField(null=True, upload_to='user/works'),
        ),
        migrations.AddField(
            model_name='skillmore',
            name='skill_icon',
            field=models.ImageField(null=True, upload_to='user/what_im_good_icon'),
        ),
        migrations.AlterField(
            model_name='mywork',
            name='git_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_img',
            field=models.ImageField(null=True, upload_to='user/skills'),
        ),
    ]
