# Generated by Django 3.1.6 on 2021-02-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210213_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='user_name2',
            new_name='user_name',
        ),
    ]
